CREATE TABLE `queue` (
  `queue_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `location_id` int(11) NOT NULL,
  `service` int(11) NOT NULL,
  `creator` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `retired` tinyint(1) NOT NULL DEFAULT 0,
  `retired_by` int(11) DEFAULT NULL,
  `date_retired` datetime DEFAULT NULL,
  `retire_reason` varchar(255) DEFAULT NULL,
  `uuid` varchar(38) NOT NULL,
  `priority_concept_set` int(11) DEFAULT NULL,
  `status_concept_set` int(11) DEFAULT NULL,
  PRIMARY KEY (`queue_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `queue_creator_fk` (`creator`),
  KEY `queue_changed_by_fk` (`changed_by`),
  KEY `queue_retired_by_fk` (`retired_by`),
  KEY `queue_location_id_fk` (`location_id`),
  KEY `queue_service_fk` (`service`),
  KEY `queue_priority_concept_set_fk` (`priority_concept_set`),
  KEY `queue_status_concept_set_fk` (`status_concept_set`),
  CONSTRAINT `queue_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_location_id_fk` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`),
  CONSTRAINT `queue_priority_concept_set_fk` FOREIGN KEY (`priority_concept_set`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `queue_retired_by_fk` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_service_fk` FOREIGN KEY (`service`) REFERENCES `concept` (`concept_id`),
  CONSTRAINT `queue_status_concept_set_fk` FOREIGN KEY (`status_concept_set`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `queue_entry` (
  `queue_entry_id` int(11) NOT NULL AUTO_INCREMENT,
  `queue_id` int(11) NOT NULL,
  `patient_id` int(11) NOT NULL,
  `priority` int(11) NOT NULL,
  `priority_comment` varchar(255) DEFAULT NULL,
  `status` int(11) NOT NULL,
  `sort_weight` double DEFAULT NULL,
  `location_waiting_for` int(11) DEFAULT NULL,
  `provider_waiting_for` int(11) DEFAULT NULL,
  `started_at` datetime NOT NULL,
  `ended_at` datetime DEFAULT NULL,
  `creator` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  `queue_coming_from` int(11) DEFAULT NULL,
  `visit_id` int(11) DEFAULT NULL,
  PRIMARY KEY (`queue_entry_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `queue_entry_creator_fk` (`creator`),
  KEY `queue_entry_changed_by_fk` (`changed_by`),
  KEY `queue_entry_voided_by_fk` (`voided_by`),
  KEY `queue_entry_queue_id_fk` (`queue_id`),
  KEY `queue_entry_patient_id_fk` (`patient_id`),
  KEY `queue_entry_priority_fk` (`priority`),
  KEY `queue_entry_status_fk` (`status`),
  KEY `queue_entry_location_waiting_for_fk` (`location_waiting_for`),
  KEY `queue_entry_provider_waiting_for_fk` (`provider_waiting_for`),
  KEY `queue_entry_queue_coming_from_id_fk` (`queue_coming_from`),
  KEY `queue_entry_visit_id_fk` (`visit_id`),
  CONSTRAINT `queue_entry_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_entry_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_entry_location_waiting_for_fk` FOREIGN KEY (`location_waiting_for`) REFERENCES `location` (`location_id`),
  CONSTRAINT `queue_entry_patient_id_fk` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`patient_id`),
  CONSTRAINT `queue_entry_priority_fk` FOREIGN KEY (`priority`) REFERENCES `concept` (`concept_id`),
  CONSTRAINT `queue_entry_provider_waiting_for_fk` FOREIGN KEY (`provider_waiting_for`) REFERENCES `provider` (`provider_id`),
  CONSTRAINT `queue_entry_queue_coming_from_id_fk` FOREIGN KEY (`queue_coming_from`) REFERENCES `queue` (`queue_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `queue_entry_queue_id_fk` FOREIGN KEY (`queue_id`) REFERENCES `queue` (`queue_id`),
  CONSTRAINT `queue_entry_status_fk` FOREIGN KEY (`status`) REFERENCES `concept` (`concept_id`),
  CONSTRAINT `queue_entry_visit_id_fk` FOREIGN KEY (`visit_id`) REFERENCES `visit` (`visit_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `queue_entry_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `queue_room` (
  `queue_room_id` int(11) NOT NULL AUTO_INCREMENT,
  `queue_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(255) DEFAULT NULL,
  `creator` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `retired` tinyint(1) NOT NULL DEFAULT 0,
  `retired_by` int(11) DEFAULT NULL,
  `date_retired` datetime DEFAULT NULL,
  `retire_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`queue_room_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `queue_room_creator_fk` (`creator`),
  KEY `queue_room_changed_by_fk` (`changed_by`),
  KEY `queue_room_voided_by_fk` (`retired_by`),
  KEY `queue_room_queue_id_fk` (`queue_id`),
  CONSTRAINT `queue_room_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_room_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `queue_room_queue_id_fk` FOREIGN KEY (`queue_id`) REFERENCES `queue` (`queue_id`),
  CONSTRAINT `queue_room_voided_by_fk` FOREIGN KEY (`retired_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
