CREATE TABLE `stockmgmt_batch_job` (
  `batch_job_id` int(11) NOT NULL AUTO_INCREMENT,
  `batch_job_type` varchar(50) NOT NULL,
  `status` varchar(50) NOT NULL,
  `description` varchar(255) NOT NULL,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `expiration` datetime DEFAULT NULL,
  `parameters` varchar(5000) NOT NULL,
  `privilege_scope` varchar(255) DEFAULT NULL,
  `location_scope` int(11) DEFAULT NULL,
  `execution_state` varchar(5000) DEFAULT NULL,
  `cancelled_by` int(11) DEFAULT NULL,
  `cancelled_date` datetime DEFAULT NULL,
  `cancel_reason` varchar(500) DEFAULT NULL,
  `exit_message` varchar(2500) DEFAULT NULL,
  `completed_date` datetime DEFAULT NULL,
  `output_artifact_size` bigint(20) DEFAULT NULL,
  `output_artifact_file_ext` varchar(10) DEFAULT NULL,
  `output_artifact_viewable` tinyint(1) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`batch_job_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_batch_job_cancelled_by_fk` (`cancelled_by`),
  KEY `stockmgmt_batch_job_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_batch_job_creator_fk` (`creator`),
  KEY `stockmgmt_batch_job_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_batch_job_location_fk` (`location_scope`),
  CONSTRAINT `stockmgmt_batch_job_cancelled_by_fk` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_batch_job_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_batch_job_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_batch_job_location_fk` FOREIGN KEY (`location_scope`) REFERENCES `location` (`location_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_batch_job_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_batch_job_owner` (
  `batch_job_owner_id` int(11) NOT NULL AUTO_INCREMENT,
  `batch_job_id` int(11) NOT NULL,
  `owner` int(11) NOT NULL,
  `date_created` datetime NOT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`batch_job_owner_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_batch_job_owner_batch_job_fk` (`batch_job_id`),
  KEY `stockmgmt_batch_job_owner_owner_fk` (`owner`),
  CONSTRAINT `stockmgmt_batch_job_owner_batch_job_fk` FOREIGN KEY (`batch_job_id`) REFERENCES `stockmgmt_batch_job` (`batch_job_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_batch_job_owner_owner_fk` FOREIGN KEY (`owner`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_location_tree` (
  `stockmgmt_location_tree_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_location_id` int(11) NOT NULL,
  `child_location_id` int(11) NOT NULL,
  `depth` int(11) NOT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stockmgmt_location_tree_id`),
  UNIQUE KEY `uuid` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_operation_type_location_scope` (
  `stock_operation_type_location_scope_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_operation_type_id` int(11) NOT NULL,
  `location_tag` varchar(50) NOT NULL,
  `is_source` tinyint(1) NOT NULL DEFAULT 0,
  `is_destination` tinyint(1) NOT NULL DEFAULT 0,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_operation_type_location_scope_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_operation_type_location_scope_creator_fk` (`creator`),
  KEY `stockmgmt_operation_type_location_scope_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_operation_type_location_scope_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_operation_type_loc_scope_on_operation_type_fk` (`stock_operation_type_id`),
  CONSTRAINT `stockmgmt_operation_type_loc_scope_on_operation_type_fk` FOREIGN KEY (`stock_operation_type_id`) REFERENCES `stockmgmt_stock_operation_type` (`stock_operation_type_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_order_item` (
  `order_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `order_id` int(11) NOT NULL,
  `stock_item_id` int(11) NOT NULL,
  `stock_item_packaging_uom_id` int(11) NOT NULL,
  `created_from` int(11) NOT NULL,
  `fulfilment_location_id` int(11) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`order_item_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_order_item_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_order_item_creator_fk` (`creator`),
  KEY `stockmgmt_order_item_stock_item_fk` (`stock_item_id`),
  KEY `stockmgmt_order_item_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_order_item_packaging_uom_fk` (`stock_item_packaging_uom_id`),
  KEY `stockmgmt_order_item_order_fk` (`order_id`),
  KEY `stockmgmt_order_item_created_from_fk` (`created_from`),
  KEY `stockmgmt_order_item_fulfilment_loc_fk` (`fulfilment_location_id`),
  CONSTRAINT `stockmgmt_order_item_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_created_from_fk` FOREIGN KEY (`created_from`) REFERENCES `location` (`location_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_fulfilment_loc_fk` FOREIGN KEY (`fulfilment_location_id`) REFERENCES `location` (`location_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_order_fk` FOREIGN KEY (`order_id`) REFERENCES `orders` (`order_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_packaging_uom_fk` FOREIGN KEY (`stock_item_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_order_item_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_party` (
  `party_id` int(11) NOT NULL AUTO_INCREMENT,
  `location_id` int(11) DEFAULT NULL,
  `stock_source_id` int(11) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`party_id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `stockmgmt_party_location_source_uk` (`location_id`,`stock_source_id`),
  KEY `stockmgmt_party_creator_fk` (`creator`),
  KEY `stockmgmt_party_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_party_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_party_stock_source_fk` (`stock_source_id`),
  CONSTRAINT `stockmgmt_party_location_fk` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`),
  CONSTRAINT `stockmgmt_party_stock_source_fk` FOREIGN KEY (`stock_source_id`) REFERENCES `stockmgmt_stock_source` (`stock_source_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_reservation_transaction` (
  `stock_item_transaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_operation_id` int(11) DEFAULT NULL,
  `stock_operation_item_id` int(11) DEFAULT NULL,
  `stock_item_id` int(11) NOT NULL,
  `stock_item_packaging_uom_id` int(11) NOT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `stock_batch_id` int(11) NOT NULL,
  `party_id` int(11) DEFAULT NULL,
  `patient_id` int(11) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `uuid` char(38) NOT NULL,
  `is_available` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`stock_item_transaction_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_reservation_transaction_batch_fk` (`stock_batch_id`),
  KEY `stockmgmt_reservation_transaction_creator_fk` (`creator`),
  KEY `stockmgmt_reservation_transaction_item_fk` (`stock_item_id`),
  KEY `stockmgmt_reservation_transaction_operation_fk` (`stock_operation_id`),
  KEY `stockmgmt_reservation_transaction_soi_fk` (`stock_operation_item_id`),
  KEY `stockmgmt_reservation_transaction_packaging_uom_fk` (`stock_item_packaging_uom_id`),
  KEY `stockmgmt_reservation_transaction_party_fk` (`party_id`),
  KEY `stockmgmt_reservation_transaction_patient_fk` (`patient_id`),
  CONSTRAINT `stockmgmt_reservation_transaction_batch_fk` FOREIGN KEY (`stock_batch_id`) REFERENCES `stockmgmt_stock_batch` (`stock_batch_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_operation_fk` FOREIGN KEY (`stock_operation_id`) REFERENCES `stockmgmt_stock_operation` (`stock_operation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_packaging_uom_fk` FOREIGN KEY (`stock_item_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_party_fk` FOREIGN KEY (`party_id`) REFERENCES `stockmgmt_party` (`party_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_patient_fk` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`patient_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_reservation_transaction_soi_fk` FOREIGN KEY (`stock_operation_item_id`) REFERENCES `stockmgmt_stock_operation_item` (`stock_operation_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_batch` (
  `stock_batch_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_item_id` int(11) NOT NULL,
  `batch_no` varchar(50) NOT NULL,
  `expiration` date DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  `expiry_notification_date` datetime DEFAULT NULL,
  PRIMARY KEY (`stock_batch_id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `stock_item_batch_no_expiration` (`stock_item_id`,`batch_no`,`expiration`),
  KEY `stockmgmt_stock_batch_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_batch_creator_fk` (`creator`),
  KEY `stockmgmt_stock_batch_stock_item_fk` (`stock_item_id`),
  KEY `stockmgmt_stock_batch_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_stock_batch_expiration_ix` (`expiration`,`expiry_notification_date`,`voided`),
  CONSTRAINT `stockmgmt_stock_batch_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_batch_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_batch_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_batch_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_item` (
  `stock_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `drug_id` int(11) DEFAULT NULL,
  `concept_id` int(11) DEFAULT NULL,
  `has_expiration` tinyint(1) NOT NULL DEFAULT 0,
  `preferred_vendor_id` int(11) DEFAULT NULL,
  `purchase_price` decimal(10,2) DEFAULT NULL,
  `purchase_price_uom_id` int(11) DEFAULT NULL,
  `dispensing_unit_id` int(11) DEFAULT NULL,
  `dispensing_unit_packaging_uom_id` int(11) DEFAULT NULL,
  `default_stock_operations_uom_id` int(11) DEFAULT NULL,
  `common_name` varchar(255) DEFAULT NULL,
  `acronym` varchar(255) DEFAULT NULL,
  `is_drug` tinyint(1) NOT NULL,
  `reorder_level` decimal(10,2) DEFAULT NULL,
  `reorder_level_uom_id` int(11) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  `category_id` int(11) DEFAULT NULL,
  `expiry_notice` int(11) DEFAULT NULL,
  PRIMARY KEY (`stock_item_id`),
  UNIQUE KEY `uuid` (`uuid`),
  UNIQUE KEY `drug_id_concept_id_index` (`drug_id`,`concept_id`),
  KEY `stockmgmt_stock_item_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_item_concept_id_fk` (`concept_id`),
  KEY `stockmgmt_stock_item_creator_fk` (`creator`),
  KEY `stockmgmt_stock_item_drug_id_fk` (`drug_id`),
  KEY `stockmgmt_stock_item_preferred_vendor_id_fk` (`preferred_vendor_id`),
  KEY `stockmgmt_stock_item_purchase_price_uom_id_fk` (`purchase_price_uom_id`),
  KEY `stockmgmt_stock_item_df_stock_operations_uom_id_fk` (`default_stock_operations_uom_id`),
  KEY `stockmgmt_stock_item_reorder_level_uom_id_fk` (`reorder_level_uom_id`),
  KEY `stockmgmt_stock_item_du_packaging_uom_id_fk` (`dispensing_unit_packaging_uom_id`),
  KEY `stockmgmt_stock_item_dispensing_unit_id_fk` (`dispensing_unit_id`),
  KEY `stockmgmt_stock_item_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_stock_item_category_id_fk` (`category_id`),
  CONSTRAINT `stockmgmt_stock_item_category_id_fk` FOREIGN KEY (`category_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_concept_id_fk` FOREIGN KEY (`concept_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_df_stock_operations_uom_id_fk` FOREIGN KEY (`default_stock_operations_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_dispensing_unit_id_fk` FOREIGN KEY (`dispensing_unit_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_drug_id_fk` FOREIGN KEY (`drug_id`) REFERENCES `drug` (`drug_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_du_packaging_uom_id_fk` FOREIGN KEY (`dispensing_unit_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_preferred_vendor_id_fk` FOREIGN KEY (`preferred_vendor_id`) REFERENCES `stockmgmt_stock_source` (`stock_source_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_purchase_price_uom_id_fk` FOREIGN KEY (`purchase_price_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_reorder_level_uom_id_fk` FOREIGN KEY (`reorder_level_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_item_packaging_uom` (
  `stock_item_packaging_uom_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_item_id` int(11) NOT NULL,
  `packaging_uom_id` int(11) DEFAULT NULL,
  `factor` decimal(10,2) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_item_packaging_uom_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_item_packaging_uom_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_item_packaging_uom_concept_fk` (`packaging_uom_id`),
  KEY `stockmgmt_stock_item_packaging_uom_creator_fk` (`creator`),
  KEY `stockmgmt_stock_item_packaging_uom_stock_item_fk` (`stock_item_id`),
  KEY `stockmgmt_stock_item_packaging_uom_voided_by_fk` (`voided_by`),
  CONSTRAINT `stockmgmt_stock_item_packaging_uom_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_packaging_uom_concept_fk` FOREIGN KEY (`packaging_uom_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_packaging_uom_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_packaging_uom_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_packaging_uom_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_item_reference` (
  `stock_item_reference_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_source_id` int(11) NOT NULL,
  `stock_item_id` int(11) NOT NULL,
  `stock_reference_code` varchar(255) NOT NULL,
  `creator` int(11) NOT NULL,
  `date_created` date DEFAULT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` date DEFAULT NULL,
  `voided` tinyint(1) DEFAULT NULL,
  `date_voided` date DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` varchar(38) NOT NULL DEFAULT 'false',
  PRIMARY KEY (`stock_item_reference_id`),
  UNIQUE KEY `stockmgmt_stock_item_reference_source_code_pk` (`stock_reference_code`,`stock_source_id`),
  KEY `stock_item_reference_stock_item_stock_item_id_fk` (`stock_item_id`),
  KEY `stock_item_reference_stock_source_stock_source_id_fk` (`stock_source_id`),
  KEY `stock_item_reference_users_changed_by_id_fk` (`changed_by`),
  KEY `stock_item_reference_users_creator_id_fk` (`creator`),
  KEY `stock_item_reference_users_voided_by_id_fk` (`voided_by`),
  CONSTRAINT `stock_item_reference_stock_item_stock_item_id_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`),
  CONSTRAINT `stock_item_reference_stock_source_stock_source_id_fk` FOREIGN KEY (`stock_source_id`) REFERENCES `stockmgmt_stock_source` (`stock_source_id`),
  CONSTRAINT `stock_item_reference_users_changed_by_id_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`),
  CONSTRAINT `stock_item_reference_users_creator_id_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`),
  CONSTRAINT `stock_item_reference_users_voided_by_id_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_item_transaction` (
  `stock_item_transaction_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_operation_id` int(11) DEFAULT NULL,
  `stock_operation_item_id` int(11) DEFAULT NULL,
  `stock_item_id` int(11) NOT NULL,
  `stock_item_packaging_uom_id` int(11) NOT NULL,
  `quantity` decimal(10,2) NOT NULL,
  `stock_batch_id` int(11) NOT NULL,
  `party_id` int(11) DEFAULT NULL,
  `patient_id` int(11) DEFAULT NULL,
  `order_id` int(11) DEFAULT NULL,
  `encounter_id` int(11) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_item_transaction_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_item_transaction_batch_fk` (`stock_batch_id`),
  KEY `stockmgmt_stock_item_transaction_creator_fk` (`creator`),
  KEY `stockmgmt_stock_item_transaction_item_fk` (`stock_item_id`),
  KEY `stockmgmt_stock_item_transaction_operation_fk` (`stock_operation_id`),
  KEY `stockmgmt_stock_item_transaction_soi_fk` (`stock_operation_item_id`),
  KEY `stockmgmt_stock_item_transaction_packaging_uom_fk` (`stock_item_packaging_uom_id`),
  KEY `stockmgmt_stock_item_transaction_party_fk` (`party_id`),
  KEY `stockmgmt_stock_item_transaction_patient_fk` (`patient_id`),
  KEY `stockmgmt_stock_item_transaction_order_fk` (`order_id`),
  KEY `stockmgmt_stock_item_transaction_encounter_fk` (`encounter_id`),
  KEY `stockmgmt_stock_item_transaction_itemsearch_fk` (`party_id`,`stock_item_id`,`stock_batch_id`,`date_created`),
  KEY `stockmgmt_stock_item_txn_itemsearch_date_fk` (`party_id`,`stock_item_id`,`date_created`),
  CONSTRAINT `stockmgmt_stock_item_transaction_batch_fk` FOREIGN KEY (`stock_batch_id`) REFERENCES `stockmgmt_stock_batch` (`stock_batch_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_encounter_fk` FOREIGN KEY (`encounter_id`) REFERENCES `encounter` (`encounter_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_operation_fk` FOREIGN KEY (`stock_operation_id`) REFERENCES `stockmgmt_stock_operation` (`stock_operation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_order_fk` FOREIGN KEY (`order_id`) REFERENCES `drug_order` (`order_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_packaging_uom_fk` FOREIGN KEY (`stock_item_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_party_fk` FOREIGN KEY (`party_id`) REFERENCES `stockmgmt_party` (`party_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_patient_fk` FOREIGN KEY (`patient_id`) REFERENCES `patient` (`patient_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_item_transaction_soi_fk` FOREIGN KEY (`stock_operation_item_id`) REFERENCES `stockmgmt_stock_operation_item` (`stock_operation_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_operation` (
  `stock_operation_id` int(11) NOT NULL AUTO_INCREMENT,
  `operation_type_id` int(11) NOT NULL,
  `status` varchar(50) NOT NULL,
  `operation_date` datetime NOT NULL,
  `operation_number` varchar(255) DEFAULT NULL,
  `external_reference` varchar(50) DEFAULT NULL,
  `remarks` varchar(255) DEFAULT NULL,
  `reason_id` int(11) DEFAULT NULL,
  `at_location_id` int(11) NOT NULL,
  `source_id` int(11) DEFAULT NULL,
  `destination_id` int(11) DEFAULT NULL,
  `operation_order` int(11) DEFAULT NULL,
  `locked` tinyint(1) NOT NULL DEFAULT 0,
  `completed_by` int(11) DEFAULT NULL,
  `completed_date` datetime DEFAULT NULL,
  `cancelled_by` int(11) DEFAULT NULL,
  `cancelled_date` datetime DEFAULT NULL,
  `cancel_reason` varchar(500) DEFAULT NULL,
  `return_reason` varchar(500) DEFAULT NULL,
  `reject_reason` varchar(500) DEFAULT NULL,
  `approval_required` tinyint(1) DEFAULT NULL,
  `responsible_person` int(11) DEFAULT NULL,
  `responsible_person_other` varchar(150) DEFAULT NULL,
  `submitted_by` int(11) DEFAULT NULL,
  `submitted_date` datetime DEFAULT NULL,
  `dispatched_by` int(11) DEFAULT NULL,
  `dispatched_date` datetime DEFAULT NULL,
  `returned_by` int(11) DEFAULT NULL,
  `returned_date` datetime DEFAULT NULL,
  `rejected_by` int(11) DEFAULT NULL,
  `rejected_date` datetime DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_operation_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_operation_cancelled_by_fk` (`cancelled_by`),
  KEY `stockmgmt_stock_operation_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_operation_completed_by_fk` (`completed_by`),
  KEY `stockmgmt_stock_operation_submitted_by_fk` (`submitted_by`),
  KEY `stockmgmt_stock_operation_dispatched_by_fk` (`dispatched_by`),
  KEY `stockmgmt_stock_operation_returned_by_fk` (`returned_by`),
  KEY `stockmgmt_stock_operation_rejected_by_fk` (`rejected_by`),
  KEY `stockmgmt_stock_operation_creator_fk` (`creator`),
  KEY `stockmgmt_stock_operation_destination_fk` (`destination_id`),
  KEY `stockmgmt_stock_operation_location_fk` (`at_location_id`),
  KEY `stockmgmt_stock_operation_reason_fk` (`reason_id`),
  KEY `stockmgmt_stock_operation_source_fk` (`source_id`),
  KEY `stockmgmt_stock_operation_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_so_responsible_person_fk` (`responsible_person`),
  KEY `stockmgmt_stock_operation_operation_type_fk` (`operation_type_id`),
  CONSTRAINT `stockmgmt_so_responsible_person_fk` FOREIGN KEY (`responsible_person`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_cancelled_by_fk` FOREIGN KEY (`cancelled_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_completed_by_fk` FOREIGN KEY (`completed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_destination_fk` FOREIGN KEY (`destination_id`) REFERENCES `stockmgmt_party` (`party_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_dispatched_by_fk` FOREIGN KEY (`dispatched_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_location_fk` FOREIGN KEY (`at_location_id`) REFERENCES `location` (`location_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_operation_type_fk` FOREIGN KEY (`operation_type_id`) REFERENCES `stockmgmt_stock_operation_type` (`stock_operation_type_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_reason_fk` FOREIGN KEY (`reason_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_rejected_by_fk` FOREIGN KEY (`rejected_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_returned_by_fk` FOREIGN KEY (`returned_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_source_fk` FOREIGN KEY (`source_id`) REFERENCES `stockmgmt_party` (`party_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_submitted_by_fk` FOREIGN KEY (`submitted_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_operation_item` (
  `stock_operation_item_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_operation_id` int(11) NOT NULL,
  `stock_item_id` int(11) NOT NULL,
  `stock_item_packaging_uom_id` int(11) DEFAULT NULL,
  `quantity` decimal(10,2) DEFAULT NULL,
  `purchase_price` decimal(10,2) DEFAULT NULL,
  `stock_batch_id` int(11) DEFAULT NULL,
  `qty_rcvd_packaging_uom_id` int(11) DEFAULT NULL,
  `quantity_received` decimal(10,2) DEFAULT NULL,
  `quantity_requested` decimal(10,2) DEFAULT NULL,
  `qty_req_packaging_uom_id` int(11) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `date_voided` datetime DEFAULT NULL,
  `voided_by` int(11) DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_operation_item_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_operation_item_creator_fk` (`creator`),
  KEY `stockmgmt_stock_operation_item_batch_fk` (`stock_batch_id`),
  KEY `stockmgmt_stock_operation_item_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_operation_item_packaging_uom_fk` (`stock_item_packaging_uom_id`),
  KEY `stockmgmt_stock_oi_qty_rcvd_pkg_uom_fk` (`qty_rcvd_packaging_uom_id`),
  KEY `stockmgmt_stock_oi_qty_req_pkg_uom_fk` (`qty_req_packaging_uom_id`),
  KEY `stockmgmt_stock_operation_item_stock_item_fk` (`stock_item_id`),
  KEY `stockmgmt_stock_operation_item_stock_operation_fk` (`stock_operation_id`),
  KEY `stockmgmt_stock_operation_item_voided_by_fk` (`voided_by`),
  CONSTRAINT `stockmgmt_stock_oi_qty_rcvd_pkg_uom_fk` FOREIGN KEY (`qty_rcvd_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_oi_qty_req_pkg_uom_fk` FOREIGN KEY (`qty_req_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_batch_fk` FOREIGN KEY (`stock_batch_id`) REFERENCES `stockmgmt_stock_batch` (`stock_batch_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_packaging_uom_fk` FOREIGN KEY (`stock_item_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_stock_op_fk` FOREIGN KEY (`stock_operation_id`) REFERENCES `stockmgmt_stock_operation` (`stock_operation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_item_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_operation_link` (
  `stock_operation_link_id` int(11) NOT NULL AUTO_INCREMENT,
  `parent_stock_operation_id` int(11) NOT NULL,
  `child_stock_operation_id` int(11) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_operation_link_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_operation_link_creator_fk` (`creator`),
  KEY `stockmgmt_stock_operation_link_pso_fk` (`parent_stock_operation_id`),
  KEY `stockmgmt_stock_operation_link_cso_fk` (`child_stock_operation_id`),
  KEY `stockmgmt_stock_operation_link_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_operation_link_voided_by_fk` (`voided_by`),
  CONSTRAINT `stockmgmt_stock_operation_link_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_link_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_link_cso_fk` FOREIGN KEY (`child_stock_operation_id`) REFERENCES `stockmgmt_stock_operation` (`stock_operation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_link_pso_fk` FOREIGN KEY (`parent_stock_operation_id`) REFERENCES `stockmgmt_stock_operation` (`stock_operation_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_link_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_operation_type` (
  `stock_operation_type_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL DEFAULT '',
  `description` varchar(1024) DEFAULT '',
  `operation_type` varchar(255) NOT NULL,
  `has_source` tinyint(1) DEFAULT NULL,
  `source_type` varchar(50) DEFAULT NULL,
  `has_destination` tinyint(1) DEFAULT NULL,
  `destination_type` varchar(50) DEFAULT NULL,
  `acronym` varchar(10) DEFAULT NULL,
  `available_when_reserved` tinyint(1) DEFAULT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  `notify_submitted` tinyint(1) NOT NULL DEFAULT 0,
  `notify_approved` tinyint(1) NOT NULL DEFAULT 0,
  `notify_completed` tinyint(1) NOT NULL DEFAULT 0,
  `notify_cancelled` tinyint(1) NOT NULL DEFAULT 0,
  `notify_rejected` tinyint(1) NOT NULL DEFAULT 0,
  `notify_returned` tinyint(1) NOT NULL DEFAULT 0,
  `notify_dispatched` tinyint(1) NOT NULL DEFAULT 0,
  `allow_expired_batch_numbers` tinyint(1) NOT NULL DEFAULT 0,
  `allow_batch_info_update` tinyint(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`stock_operation_type_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_operation_type_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_operation_type_creator_fk` (`creator`),
  KEY `stockmgmt_stock_operation_type_voided_by_fk` (`voided_by`),
  CONSTRAINT `stockmgmt_stock_operation_type_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_type_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_operation_type_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_rule` (
  `stock_rule_id` int(11) NOT NULL AUTO_INCREMENT,
  `stock_item_id` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `description` varchar(500) DEFAULT NULL,
  `location_id` int(11) NOT NULL,
  `quantity` decimal(10,2) DEFAULT NULL,
  `stock_item_packaging_uom_id` int(11) DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL,
  `evaluation_frequency` bigint(20) NOT NULL,
  `last_evaluation` datetime DEFAULT NULL,
  `next_evaluation` datetime DEFAULT NULL,
  `action_frequency` bigint(20) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  `alert_role` varchar(50) DEFAULT NULL,
  `mail_role` varchar(50) DEFAULT NULL,
  `last_action_date` datetime DEFAULT NULL,
  `enable_descendants` tinyint(1) NOT NULL DEFAULT 0,
  `next_action_date` datetime DEFAULT NULL,
  PRIMARY KEY (`stock_rule_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_rule_creator_fk` (`creator`),
  KEY `stockmgmt_stock_rule_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_rule_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_stock_rule_on_stock_item_fk` (`stock_item_id`),
  KEY `stockmgmt_stock_rule_on_stock_item_packaging_uom_fk` (`stock_item_packaging_uom_id`),
  KEY `stockmgmt_stock_rule_on_location_fk` (`location_id`),
  CONSTRAINT `stockmgmt_stock_rule_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_rule_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_rule_on_location_fk` FOREIGN KEY (`location_id`) REFERENCES `location` (`location_id`),
  CONSTRAINT `stockmgmt_stock_rule_on_stock_item_fk` FOREIGN KEY (`stock_item_id`) REFERENCES `stockmgmt_stock_item` (`stock_item_id`),
  CONSTRAINT `stockmgmt_stock_rule_on_stock_item_packaging_uom_fk` FOREIGN KEY (`stock_item_packaging_uom_id`) REFERENCES `stockmgmt_stock_item_packaging_uom` (`stock_item_packaging_uom_id`),
  CONSTRAINT `stockmgmt_stock_rule_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_stock_source` (
  `stock_source_id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `acronym` varchar(255) NOT NULL,
  `source_type_id` int(11) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`stock_source_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_stock_source_type_fk` (`source_type_id`),
  KEY `stockmgmt_stock_source_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_stock_source_creator_fk` (`creator`),
  KEY `stockmgmt_stock_source_voided_by_fk` (`voided_by`),
  CONSTRAINT `stockmgmt_stock_source_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_source_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_source_type_fk` FOREIGN KEY (`source_type_id`) REFERENCES `concept` (`concept_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_stock_source_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_user_role_scope` (
  `user_role_scope_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `role` varchar(50) NOT NULL,
  `is_permanent` tinyint(1) NOT NULL,
  `active_from` datetime DEFAULT NULL,
  `active_to` datetime DEFAULT NULL,
  `enabled` tinyint(1) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`user_role_scope_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_user_role_scope_creator_fk` (`creator`),
  KEY `stockmgmt_user_role_scope_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_user_role_scope_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_user_role_scope_user_fk` (`user_id`),
  KEY `stockmgmt_user_role_scope_role_fk` (`role`),
  CONSTRAINT `stockmgmt_user_role_scope_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_role_fk` FOREIGN KEY (`role`) REFERENCES `role` (`role`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_user_fk` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_user_role_scope_location` (
  `user_role_scope_location_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_role_scope_id` int(11) NOT NULL,
  `location_id` int(11) NOT NULL,
  `enable_descendants` tinyint(1) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`user_role_scope_location_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_user_role_scope_location_creator_fk` (`creator`),
  KEY `stockmgmt_user_role_scope_location_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_user_role_scope_location_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_user_role_scope_location_on_user_role_scope_fk` (`user_role_scope_id`),
  CONSTRAINT `stockmgmt_user_role_scope_location_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_location_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_location_on_user_role_scope_fk` FOREIGN KEY (`user_role_scope_id`) REFERENCES `stockmgmt_user_role_scope` (`user_role_scope_id`),
  CONSTRAINT `stockmgmt_user_role_scope_location_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
CREATE TABLE `stockmgmt_user_role_scope_operation_type` (
  `user_role_scope_operation_type_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_role_scope_id` int(11) NOT NULL,
  `operation_type_id` int(11) NOT NULL,
  `creator` int(11) NOT NULL DEFAULT 0,
  `date_created` datetime NOT NULL,
  `changed_by` int(11) DEFAULT NULL,
  `date_changed` datetime DEFAULT NULL,
  `voided` tinyint(1) NOT NULL DEFAULT 0,
  `voided_by` int(11) DEFAULT NULL,
  `date_voided` datetime DEFAULT NULL,
  `void_reason` varchar(255) DEFAULT NULL,
  `uuid` char(38) NOT NULL,
  PRIMARY KEY (`user_role_scope_operation_type_id`),
  UNIQUE KEY `uuid` (`uuid`),
  KEY `stockmgmt_user_role_scope_operation_type_creator_fk` (`creator`),
  KEY `stockmgmt_user_role_scope_operation_type_changed_by_fk` (`changed_by`),
  KEY `stockmgmt_user_role_scope_operation_type_voided_by_fk` (`voided_by`),
  KEY `stockmgmt_user_role_scope_operation_type_on_operation_type_fk` (`operation_type_id`),
  KEY `stockmgmt_user_role_scope_operation_type_on_user_role_scope_fk` (`user_role_scope_id`),
  CONSTRAINT `stockmgmt_user_role_scope_operation_type_changed_by_fk` FOREIGN KEY (`changed_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_operation_type_creator_fk` FOREIGN KEY (`creator`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `stockmgmt_user_role_scope_operation_type_on_operation_type_fk` FOREIGN KEY (`operation_type_id`) REFERENCES `stockmgmt_stock_operation_type` (`stock_operation_type_id`),
  CONSTRAINT `stockmgmt_user_role_scope_operation_type_on_user_role_scope_fk` FOREIGN KEY (`user_role_scope_id`) REFERENCES `stockmgmt_user_role_scope` (`user_role_scope_id`),
  CONSTRAINT `stockmgmt_user_role_scope_operation_type_voided_by_fk` FOREIGN KEY (`voided_by`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;
